FROM python:3.8

WORKDIR /orchestration
COPY ./requirements_orchestration.txt /orchestration/requirements.txt
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r /orchestration/requirements.txt
COPY ./orchestration /orchestration/orchestration
COPY ./utility /orchestration/utility

EXPOSE 8000
CMD ["uvicorn", "orchestration.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "16"]
